// 16PF Question Bank (187 items)
// Verbatim from 16pf-platform.jsx
import type { Question } from './types';

export const QUESTIONS: Question[] = [
  { id: 1, text: "He comprendido bien las instrucciones para contestar el cuestionario", options: ["Sí", "No estoy seguro", "No"] },
  { id: 2, text: "Estoy dispuesto a contestar todas las cuestiones con sinceridad", options: ["Sí", "No estoy seguro", "No"] },
  { id: 3, text: "¿Cuáles de las siguientes palabras es diferente de las otras dos?", options: ["Algo", "Nada", "Mucho"] },
  { id: 4, text: "Poseo suficiente energía para enfrentarme a todos mis problemas", options: ["Sí", "No estoy seguro", "No"] },
  { id: 5, text: "Evito criticar a la gente y sus ideas", options: ["Sí", "Algunas veces", "No"] },
  { id: 6, text: "Hago agudas y sarcásticas observaciones a la gente si creo que las merece", options: ["Generalmente", "Algunas veces", "No"] },
  { id: 7, text: "Me gusta más la música semi clásica que las canciones populares", options: ["Generalmente", "Algunas veces", "No"] },
  { id: 8, text: "Si veo peleándose a los niños de mis vecinos", options: ["Les dejo solucionar su problema", "No estoy seguro", "Razono con ellos la solución"] },
  { id: 9, text: "En situaciones de liderazgo", options: ["Fácilmente soy de los que toma iniciativa", "Intervengo algunas veces", "Prefiero quedarme tranquilamente a distancia"] },
  { id: 10, text: "Sería más interesante ser", options: ["Ingeniero de la Construcción", "No estoy seguro entre los dos", "Escritor de Teatro"] },
  { id: 11, text: "Generalmente puedo tolerar a la gente presuntuosa, aunque fanfarronee o piense demasiado de ella misma", options: ["Sí", "Término medio", "No"] },
  { id: 12, text: "Cuando una persona no es honrada, casi siempre se le puede notar en la cara", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 13, text: "Aceptaría mejor el riesgo de un trabajo donde pudiera tener ganancias mayores, aunque eventuales, que otro con sueldo pequeño, pero seguro", options: ["Sí", "No estoy seguro", "No"] },
  { id: 14, text: "De vez en cuando siento un vago temor o un repentino miedo, sin poder comprender la razón", options: ["Sí", "Término medio", "No"] },
  { id: 15, text: "Cuando me critican duramente por algo que no he hecho", options: ["No me siento culpable", "Término medio", "Todavía me siento un poco culpable"] },
  { id: 16, text: "Casi todo se puede comprar con dinero", options: ["Sí", "No estoy seguro", "No"] },
  { id: 17, text: "La mayoría de las personas serían más felices si convivieran más con la gente de su nivel e hicieran las cosas como los demás", options: ["Sí", "Término medio", "No"] },
  { id: 18, text: "En ocasiones, mirándome en un espejo, me entran dudas sobre lo que es mi derecha o izquierda", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 19, text: "Cuando algo realmente me pone furioso, suelo calmarme muy pronto", options: ["Sí", "Término medio", "No"] },
  { id: 20, text: "Preferiría tener una casa", options: ["En un barrio con vida social", "Término medio", "Aislado en el bosque"] },
  { id: 21, text: "Con el mismo horario y sueldo, sería más interesante ser", options: ["El cocinero de un buen restaurante", "No estoy seguro entre ambos", "El que sirve las mesas en el restaurante"] },
  { id: 22, text: "<Cansado> es a <trabajar> como <orgullo> es a:", options: ["Sonreír", "Tener éxito", "Ser feliz"] },
  { id: 23, text: "Me pongo algo nervioso ante animales salvajes, incluso cuando están encerrados en fuertes jaulas", options: ["Sí", "No estoy seguro", "No"] },
  { id: 24, text: "Una ley anticuada debería cambiarse", options: ["Solo después de muchas discusiones", "Término Medio", "Inmediatamente"] },
  { id: 25, text: "La mayor parte de las personas me considera un interlocutor agradable", options: ["Sí", "No estoy seguro", "No"] },
  { id: 26, text: "Me gustaría salir a divertirme o ir a un espectáculo", options: ["Más de una vez por semana", "Alrededor de una vez por semana", "Menos de una vez por semana"] },
  { id: 27, text: "Cuando veo gente desaliñada y sucia", options: ["Lo acepto simplemente", "Término Medio", "Me disgusta y me fastidia"] },
  { id: 28, text: "Estando en un grupo social me siento un poco turbado si de pronto paso a ser el foco de atención", options: ["Sí", "Término Medio", "No"] },
  { id: 29, text: "Cuando voy por la calle prefiero detenerme antes a ver un artista pintando que a escuchar a la gente discutir", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 30, text: "Cuando me ponen al frente de algo, insisto en que se sigan mis instrucciones; en caso contrario renuncio", options: ["Sí", "Algunas veces", "No"] },
  { id: 31, text: "Sería mejor que las vacaciones fueran más largas y obligatorias para todas las personas", options: ["De acuerdo", "No estoy seguro", "Desacuerdo"] },
  { id: 32, text: "Hablo acerca de mis sentimientos", options: ["Solo si es necesario", "Término Medio", "Fácilmente, siempre que tengo ocasión"] },
  { id: 33, text: "Me siento muy abatido cuando la gente me critica en grupo", options: ["Verdadero", "Término Medio", "Falso"] },
  { id: 34, text: "Si mi jefe (profesor) me llama su despacho", options: ["Aprovecho la ocasión para pedirle algo que deseo", "Término Medio", "Temo haber hecho algo malo"] },
  { id: 35, text: "Mis decisiones se apoyan en", options: ["El corazón", "Los sentimientos y la razón por igual", "La cabeza"] },
  { id: 36, text: "En mi adolescencia pertenecía a equipos deportivos", options: ["Algunas veces", "A menudo", "La mayoría de veces"] },
  { id: 37, text: "Cuando hablo con alguien me gusta", options: ["Decir las cosas tal y como se me ocurren", "Término medio", "Organizar antes mis ideas"] },
  { id: 38, text: "A veces me pongo en estado de tensión y agitación cuando pienso en los sucesos del día", options: ["Sí", "Término medio", "No"] },
  { id: 39, text: "He sido elegido para hacer algo importante", options: ["Solo en pocas ocasiones", "Varias veces", "Muchas veces"] },
  { id: 40, text: "¿Cuáles de las siguientes cosas es diferente de las otras dos?", options: ["Vela", "Luna", "Luz eléctrica"] },
  { id: 41, text: "<Sorpresa> es a <extraño> como <miedo> es a:", options: ["Valeroso", "Ansioso", "Terrible"] },
  { id: 42, text: "A veces no puedo dormirme porque tengo una idea que me da vueltas en la cabeza", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 43, text: "Me siento desasosegado cuando trabajo en un proyecto que requiere una acción rápida que afecta a los demás", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 44, text: "Indudablemente tengo menos amigos que la mayoría de las personas", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 45, text: "Aborrecería tener que estar en un lugar donde hubiera poca gente con quien hablar", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 46, text: "Creo que es más importante mucha libertad que buena educación y respeto a la ley", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 47, text: "Siempre me alegra formar parte de un grupo grande, como una reunión, un baile o una asamblea", options: ["Sí", "Término medio", "No"] },
  { id: 48, text: "En mi época de estudiante me gustaba", options: ["La música", "No estoy seguro", "La actividad de tipo manual"] },
  { id: 49, text: "Si alguien se enfada conmigo", options: ["Intento calmarme", "No estoy seguro", "Me irrito con él"] },
  { id: 50, text: "Para los padres es más importante", options: ["Ayudar a sus hijos a desarrollarse afectivamente", "Término Medio", "Enseñarles a controlar sus emociones"] },
  { id: 51, text: "Siento de vez en cuando la necesidad de ocuparme en una actividad física enérgica", options: ["Sí", "Término medio", "No"] },
  { id: 52, text: "Hay veces que no me siento con humor para ver a alguien", options: ["Muy raramente", "Término medio", "Muy a menudo"] },
  { id: 53, text: "A veces los demás me advierten que yo muestro mi excitación demasiado claramente en la voz y en los modales", options: ["Sí", "Término medio", "No"] },
  { id: 54, text: "Lo que el mundo necesita es", options: ["Ciudadanos más sensatos y constantes", "No estoy seguro", "Más idealistas con proyectos para un mundo mejor"] },
  { id: 55, text: "Preferiría tener un negocio propio, no compartido con otra persona", options: ["Sí", "No estoy seguro", "No"] },
  { id: 56, text: "Tengo mi habitación organizada en un modo inteligente y estético, con las cosas colocadas casi siempre en lugares conocidos", options: ["Sí", "Término medio", "No"] },
  { id: 57, text: "En ocasiones dudo si la gente con quien estoy hablando se interesa realmente por lo que digo", options: ["Sí", "Término medio", "No"] },
  { id: 58, text: "Si tuviera que escoger, preferiría ser", options: ["Guarda Forestal", "No estoy Seguro", "Profesor de enseñanza media"] },
  { id: 59, text: "¿Cuál de las siguientes fracciones es diferente de las otras dos?", options: ["3/7", "3/9", "3/11"] },
  { id: 60, text: "<Tamaño> es a <longitud> como <delito> es a:", options: ["Prisión", "Castigo", "Robo"] },
  { id: 61, text: "En mi vida personal consigo casi siempre todos mis propósitos", options: ["Sí", "No estoy seguro", "No"] },
  { id: 62, text: "Tengo algunas características en las que me siento claramente superior a la mayor parte de la gente", options: ["Sí", "No estoy seguro", "No"] },
  { id: 63, text: "Solo asisto a actos sociales cuando estoy obligado, y me mantengo aparte en las demás ocasiones", options: ["Sí", "No estoy seguro", "No"] },
  { id: 64, text: "Es mejor ser cauto y esperar poco que optimista y esperar siempre el éxito", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 65, text: "Algunas veces la gente dice que soy descuidado, aunque me considero una persona agradable", options: ["Sí", "Término medio", "No"] },
  { id: 66, text: "Suelo permanecer callado delante de personas mayores (con mucha más experiencia, edad, o jerarquía)", options: ["Sí", "Término medio", "No"] },
  { id: 67, text: "Tengo un buen sentido de la orientación (sitúo fácilmente los puntos cardinales), cuando me encuentro en un lugar desconocido", options: ["Sí", "Término medio", "No"] },
  { id: 68, text: "Cuando leo una revista o un artículo tendencioso o injusto, me inclino más a olvidarlo que a replicar o 'devolver el golpe'", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 69, text: "En tareas de grupo preferiría", options: ["Intentar mejorar los preparativos", "Término medio", "Llevar las actas o registros y procurar que se cumplan las normas"] },
  { id: 70, text: "Me gustaría más andar con personas corteses que con individuos rebeldes y toscos", options: ["Sí", "Término medio", "No"] },
  { id: 71, text: "Si mis conocidos me tratan mal o muestran que yo les disgusto", options: ["No me importa nada", "Término medio", "Me siento abatido"] },
  { id: 72, text: "Siempre estoy alerta ante los intentos de propaganda en las cosas que leo", options: ["Sí", "No estoy seguro", "No"] },
  { id: 73, text: "Me gustaría gozar de la vida tranquila y a mi modo que ser admirado por mis resultados", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 74, text: "Para estar informado prefiero", options: ["Discutir los acontecimientos con la gente", "Término medio", "Apoyarme en las informaciones periodísticas de actualidad"] },
  { id: 75, text: "Me encuentro formado (maduro) para la mayor parte de las cosas", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 76, text: "Me encuentro más abatido que ayudado por el tipo de crítica que la gente suele hacer", options: ["A menudo", "Ocasionalmente", "Nunca"] },
  { id: 77, text: "En las fiestas de cumpleaños", options: ["Me gusta hacer regalos personales", "No estoy seguro", "Pienso que comprar regalos es un poco latoso"] },
  { id: 78, text: "<AB> es a <dc> como <SR> es a:", options: ["qp", "pq", "tu"] },
  { id: 79, text: "<Mejor> es a <pésimo> como <menor> es a:", options: ["Mayor", "Óptimo", "Máximo"] },
  { id: 80, text: "Mis amigas me han fallado", options: ["Muy rara vez", "Ocasionalmente", "Muchas veces"] },
  { id: 81, text: "Cuando me siento abatido hago grandes esfuerzos por ocultar mis sentimientos a los demás", options: ["A menudo", "Ocasionalmente", "Nunca"] },
  { id: 82, text: "Gasto gran parte de mi tiempo libre hablando con los amigos sobre situaciones sociales agradables vividas en el pasado", options: ["Sí", "No estoy seguro", "No"] },
  { id: 83, text: "Pensando en las dificultades de mi trabajo", options: ["Intento organizarme antes de que aparezcan", "Término medio", "Doy por supuesto que puedo dominarlas cuando vengan"] },
  { id: 84, text: "Me gusta bastante hablar o dirigir la palabra a un grupo numeroso", options: ["Sí", "Término medio", "No"] },
  { id: 85, text: "He experimentado en varias situaciones sociales el llamado 'nerviosismo del orador'", options: ["Muy frecuentemente", "Ocasionalmente", "Casi nunca"] },
  { id: 86, text: "Prefiero leer", options: ["Una narración realista de contiendas militares o políticas", "No estoy seguro", "Una novela imaginativa y delicada"] },
  { id: 87, text: "Cuando la gente autoritaria trata de dominarme, hago justamente lo contrario de lo que quiere", options: ["Sí", "Término medio", "No"] },
  { id: 88, text: "Suelo olvidar muchas cosas triviales y sin importancia, tales como los nombres de las calles y tiendas de la ciudad", options: ["Sí", "Término medio", "No"] },
  { id: 89, text: "Me gustaría la profesión de veterinario, ocupado con las enfermedades y curación de animales", options: ["Sí", "Término medio", "No"] },
  { id: 90, text: "No resulta embarazoso que me dediquen elogios o cumplidos", options: ["Sí", "Término medio", "No"] },
  { id: 91, text: "Siendo adolescente, cuando mi opinión era distinta de la de mis padres, normalmente", options: ["Mantenía mi opinión", "Término medio", "Aceptaba su autoridad"] },
  { id: 92, text: "Me gusta tomar parte activa en las tareas sociales, trabajos de comité, etc.", options: ["Sí", "Término medio", "No"] },
  { id: 93, text: "Al llevar a cabo una tarea, no estoy satisfecho hasta que se ha considerado con toda atención el menor detalle", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 94, text: "Tengo ocasiones en que me es difícil alejar un sentimiento de compasión hacia mí mismo", options: ["A menudo", "Algunas veces", "Nunca"] },
  { id: 95, text: "Siempre soy capaz de controlar perfectamente la expresión de mis sentimientos", options: ["Sí", "Término medio", "No"] },
  { id: 96, text: "Ante un invento utilitario, me gustaría", options: ["Trabajar en él en el laboratorio", "No estoy seguro", "Venderlo a la gente"] },
  { id: 97, text: "La siguiente serie de letras xooooxxoooxxx continúa con el grupo:", options: ["oxxx", "ooxx", "xooo"] },
  { id: 98, text: "Algunas veces las personas parecen ignorarme o evitarme, aunque no sé por qué", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 99, text: "La gente me trata menos razonablemente de lo que merecen mis buenas intenciones", options: ["A menudo", "Ocasionalmente", "Nunca"] },
  { id: 100, text: "Aunque no sea un grupo mixto de mujeres y hombres, me disgusta que se use un lenguaje obsceno", options: ["Sí", "Término medio", "No"] },
  { id: 101, text: "Me gusta hacer las cosas atrevidas y temerarias solo por el placer de divertirme", options: ["Sí", "Término medio", "No"] },
  { id: 102, text: "Me resulta molesta la vista de una habitación muy sucia", options: ["Sí", "Término medio", "No"] },
  { id: 103, text: "Cuando estoy en un grupo pequeño, me agrada quedarme en un segundo término y dejar que otros lleven el peso de la conversación", options: ["Sí", "Término medio", "No"] },
  { id: 104, text: "Me resulta fácil mezclarme con la gente en una reunión social", options: ["Verdadero", "No estoy segura", "Falso"] },
  { id: 105, text: "Sería más interesante ser", options: ["Orientador vocacional para ayudar a los jóvenes en la búsqueda de su profesión", "No estoy seguro", "Directivo de una empresa industrial"] },
  { id: 106, text: "Por regla general, mis jefes y mi familia me encuentran defectos solo cuando realmente existen", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 107, text: "Me disgusta el modo con que algunas personas se fijan en otras en la calle o en las tiendas", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 108, text: "Como los alimentos con gusto y placer, aunque no siempre tan cuidadosa y educadamente como otras personas", options: ["A menudo", "Ocasionalmente", "Nunca"] },
  { id: 109, text: "Temo algún castigo incluso cuando no he hecho nada malo", options: ["A menudo", "Ocasionalmente", "Nunca"] },
  { id: 110, text: "Me gustaría más tener un trabajo con", options: ["Un determinado sueldo fijo", "Término medio", "Un sueldo más alto pero siempre que demuestre a los demás que lo merezco"] },
  { id: 111, text: "Me molesta que la gente piense que mi comportamiento es demasiado raro o fuera de lo corriente", options: ["Mucho", "Algo", "Nada"] },
  { id: 112, text: "A veces dejo que sentimientos de envidia o celos influyan en mis acciones", options: ["Sí", "Término medio", "No"] },
  { id: 113, text: "En ocasiones, contrariedades muy pequeñas me irritan mucho", options: ["Sí", "Término medio", "No"] },
  { id: 114, text: "Siempre duermo bien, nunca hablo en sueños ni me levanto sonámbulo", options: ["Sí", "Término medio", "No"] },
  { id: 115, text: "Me resultaría más interesante trabajar en una empresa", options: ["Atendiendo a los clientes", "Término medio", "Llevando las cuentas o los archivos"] },
  { id: 116, text: "<Azada> es a <cavar> como <cuchillo> es a:", options: ["Cortar", "Afilar", "Picar"] },
  { id: 117, text: "Cuando la gente no es razonable yo normalmente", options: ["Me quedo tranquilo", "Término medio", "La menosprecio"] },
  { id: 118, text: "Si los demás hablan en voz alta cuando estoy escuchando música", options: ["Puedo concentrarme en ella sin que me impida", "Término medio", "Eso me impide disfrutar"] },
  { id: 119, text: "Creo que se me describe mejor como", options: ["Comedido y reposado", "Término medio", "Enérgico"] },
  { id: 120, text: "Preferiría vestirme con sencillez y corrección que con un estilo personal y llamativo", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 121, text: "Me niego a admitir sugerencias bien intencionadas de los demás aunque sé que no debería hacerlo", options: ["Algunas veces", "Casi nunca", "Nunca"] },
  { id: 122, text: "Cuando es necesario que alguien emplee algo de diplomacia y persuasión para conseguir que la gente actúe, generalmente solo me lo encargan a mí", options: ["Sí", "Término medio", "No"] },
  { id: 123, text: "Me considero a mí mismo como una persona muy abierta y sociable", options: ["Sí", "Término medio", "No"] },
  { id: 124, text: "Me gusta la música", options: ["Ligeramente movida y animada", "Término medio", "Emotiva y sentimental"] },
  { id: 125, text: "Si estoy completamente seguro de que una persona es injusta se comporta egoístamente, se lo digo incluso si esto me causa problemas", options: ["Sí", "Término medio", "No"] },
  { id: 126, text: "En un viaje largo, preferiría", options: ["A leer algo profundo pero interesante", "No estoy seguro", "Pasar el tiempo charlando cualquier cosa con un compañero de viaje"] },
  { id: 127, text: "En una situación que puede llegar a ser peligrosa, creo que es mejor alborotar o hablar alto, aun cuando se pierdan la calma y la cortesía", options: ["Sí", "Término medio", "No"] },
  { id: 128, text: "Es muy exagerada la idea de que la enfermedad proviene tanto de causas mentales como físicas", options: ["Sí", "Término medio", "No"] },
  { id: 129, text: "En cualquier gran ceremonia oficial debería mantenerse la pompa y el esplendor", options: ["Sí", "Término medio", "No"] },
  { id: 130, text: "Cuando hay que hacer algo, me gustaría más trabajar", options: ["En equipo", "No estoy seguro", "Yo solo"] },
  { id: 131, text: "Creo firmemente que tal vez el jefe no tenga siempre la razón, pero siempre tiene la razón por ser el jefe", options: ["Sí", "Término medio", "No"] },
  { id: 132, text: "Suelo enfadarme con las personas demasiado pronto", options: ["Sí", "Término medio", "No"] },
  { id: 133, text: "Siempre puedo cambiar viejos hábitos sin dificultad y sin volver a ellos", options: ["Sí", "Término medio", "No"] },
  { id: 134, text: "Si el sueldo fuera el mismo prefiero ser", options: ["Abogado", "No estoy seguro entre ambos", "Navegante o piloto"] },
  { id: 135, text: "<Llama> es a <calor> como <rosa> es a:", options: ["Espina", "Pétalo", "Aroma"] },
  { id: 136, text: "Cuando se acerca el momento de algo que he planeado y he esperado, en ocasiones pierdo ilusión por ello", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 137, text: "Puedo trabajar cuidadosamente en la mayor parte de las cosas sin que me molesten las personas que hacen mucho ruido a mi alrededor", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 138, text: "En ocasiones hablo a desconocidos sobre las cosas que considero importantes, aunque no me pregunten sobre ellas", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 139, text: "Me atrae más pasar una tarde ocupado en una tarea tranquila a la que tenga afición que estar en una reunión animada", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 140, text: "Siempre presento las reglas básicas de lo justo e injusto", options: ["Sí", "Término medio", "No"] },
  { id: 141, text: "En el trato social", options: ["Muestro mis emociones tal como las siento", "Término medio", "Guardo mis emociones para mis adentros"] },
  { id: 142, text: "Admiro más la belleza de un poema que de un arma de fuego bien construida", options: ["Sí", "Término medio", "No"] },
  { id: 143, text: "A veces digo en broma disparates, solo para sorprender a la gente y ver qué responden", options: ["Sí", "No estoy seguro", "No"] },
  { id: 144, text: "Me agradaría ser un periodista que escribiera sobre teatro, conciertos, ópera, etc.", options: ["Sí", "No estoy seguro", "No"] },
  { id: 145, text: "Nunca siento la necesidad de garabatear, dibujar o moverme cuando estoy sentado en una reunión", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 146, text: "Si alguien me dice algo que sé que no es cierto, suelo pensar", options: ["Es un mentiroso", "Término medio", "Evidentemente no está bien informado"] },
  { id: 147, text: "La gente me considera con justicia una persona activa pero con éxito solo mediano", options: ["Sí", "Término medio", "No"] },
  { id: 148, text: "Si se suscitara una controversia violenta entre otros miembros de un grupo de discusión", options: ["Me gustaría ver quién es el ganador", "Término medio", "Desearía que se suavizara de nuevo la situación"] },
  { id: 149, text: "Me gusta planear mis cosas solo, sin interrupciones y sugerencias de otros", options: ["Sí", "Término medio", "No"] },
  { id: 150, text: "Me gusta seguir mis propios caminos, en vez de actuar según normas establecidas", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 151, text: "Me pongo nervioso (tenso) cuando pienso en todas las cosas que tengo que hacer", options: ["Sí", "Algunas veces", "No"] },
  { id: 152, text: "No me perturba que la gente me haga sugerencias cuando estoy jugando", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 153, text: "Me parece más interesante ser", options: ["Artista", "No estoy seguro", "Secretario de un club social"] },
  { id: 154, text: "¿Cuál de las siguientes palabras es diferente de las otras dos?", options: ["Ancho", "Zigzag", "Recto"] },
  { id: 155, text: "He tenido sueños tan intensos que no me han dejado dormir bien", options: ["A menudo", "No estoy seguro", "No"] },
  { id: 156, text: "Aunque tengo pocas posibilidades de éxito, creo que todavía me merece la pena correr riesgo", options: ["Sí", "Término medio", "No"] },
  { id: 157, text: "Cuando yo sé muy bien lo que el grupo tiene que hacer, me gusta ser el único en dar las órdenes", options: ["Sí", "Término medio", "No"] },
  { id: 158, text: "Me considera una persona muy entusiasta", options: ["Sí", "Término medio", "No"] },
  { id: 159, text: "Soy una persona bastante estricta, e insisto siempre en hacer las cosas tan correctamente como sea posible", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 160, text: "Me disgusta un poco que la gente me esté mirando cuando trabajo", options: ["Sí", "Término medio", "No"] },
  { id: 161, text: "Como siempre es posible conseguir las cosas utilizando gradualmente métodos razonables, a veces es necesario emplear la fuerza", options: ["Sí", "Término medio", "No"] },
  { id: 162, text: "Si se pasa por alto una buena observación mía", options: ["La dejo pasar", "Término medio", "Doy a la gente oportunidad de volver a escucharla"] },
  { id: 163, text: "Me gustaría hacer el trabajo de un oficial encargado de los casos de delincuentes bajo fianza", options: ["Sí", "Término medio", "No"] },
  { id: 164, text: "Hay que ser prudente antes de mezclarse con cualquier desconocido, puesto que hay peligros de infección y de otro tipo", options: ["Sí", "No estoy seguro", "No"] },
  { id: 165, text: "En un viaje al extranjero, preferiría ir en un grupo organizado, con un experto, que planear yo mismo los lugares que deseo visitar", options: ["Sí", "No estoy seguro", "No"] },
  { id: 166, text: "Si la gente se aprovecha de mi amistad, no me quedo resentido y lo olvido pronto", options: ["Verdadero", "Término medio", "Falso"] },
  { id: 167, text: "Creo que la sociedad debería aceptar nuevas costumbres, de acuerdo con la razón, y olvidar los viejos usos y tradiciones", options: ["Sí", "Término medio", "No"] },
  { id: 168, text: "Aprendo mejor", options: ["Leyendo un libro bien escrito", "Término medio", "Participando en un grupo de discusión"] },
  { id: 169, text: "Me gusta esperar a estar seguro de que lo que voy a decir es correcto, antes de exponer mis ideas", options: ["Siempre", "Generalmente", "Solo si es posible"] },
  { id: 170, text: "Algunas veces me 'sacan de quicio' de un modo insoportable pequeñas cosas", options: ["Sí", "Término medio", "No"] },
  { id: 171, text: "No suelo decir, sin pensarlas, cosas que luego lamento mucho", options: ["Verdadero", "No estoy seguro", "Falso"] },
  { id: 172, text: "Si me pidieran colaborar en una campaña caritativa", options: ["Aceptaría", "No estoy seguro", "Diría cortésmente que estoy ocupado"] },
  { id: 173, text: "<Pronto> es a <nunca> como <cerca> es a:", options: ["En ningún sitio", "Lejos", "En otro sitio"] },
  { id: 174, text: "Si cometo una falta social desagradable, puedo olvidarla pronto", options: ["Sí", "No estoy seguro", "No"] },
  { id: 175, text: "Me considero un 'hombre de ideas' que casi siempre puede apuntar alguna solución a problemas", options: ["Sí", "Término medio", "No"] },
  { id: 176, text: "Creo que se me da mejor mostrar", options: ["Aplomo en las pugnas y discusiones de una reunión", "No estoy seguro", "Tolerancia con los demás"] },
  { id: 177, text: "Me gusta un trabajo que presente cambios, variedad y viajes, aunque impliquen algo de peligro", options: ["Sí", "Término medio", "No"] },
  { id: 178, text: "Me gusta un trabajo que requiera dotes de atención y exactitud", options: ["Sí", "Término medio", "No"] },
  { id: 179, text: "Soy de ese tipo de personas con tanta energía que siempre están ocupadas", options: ["Sí", "No estoy seguro", "No"] },
  { id: 180, text: "En mi época de estudiante prefería (prefiero)", options: ["Lengua o Literatura", "No estoy seguro", "Matemáticas o aritmética"] },
  { id: 181, text: "Algunas veces me ha turbado el que la gente diga a mi espalda cosas desagradables y sin fundamentos", options: ["Sí", "No estoy seguro", "No"] },
  { id: 182, text: "Hablar con personas corrientes, convencionales y rutinarias", options: ["Es a menudo muy interesante e instructivo", "Término medio", "Me fastidia porque no hay profundidad o se trata de chismes y cosas sin importancia"] },
  { id: 183, text: "Algunas cosas me irritan tanto que creo que entonces lo mejor es no hablar", options: ["Sí", "Término medio", "No"] },
  { id: 184, text: "En la formación del niño es más importante", options: ["Darle bastante afecto", "Término medio", "Procurar que aprenda hábitos y actividades deseables"] },
  { id: 185, text: "Los demás me consideran una persona firme e imperturbable, impasible ante los vaivenes de las circunstancias", options: ["Sí", "Término medio", "No"] },
  { id: 186, text: "Creo que en el mundo actual es más importante resolver", options: ["El problema de la intención moral", "No estoy seguro", "Los problemas políticos"] },
  { id: 187, text: "Creo que no me ha saltado ninguna cuestión y he contestado a todas de modo apropiado", options: ["Sí", "No estoy seguro", "No"] },
];
